"""Pydantic models package."""

from app.models.requests import (
    AnalyzeGameRequest,
    AnalyzePositionRequest,
    BestMoveRequest,
    EvaluateRequest,
    LegalMovesRequest,
    MultiPVRequest,
    ValidateFenRequest,
    ValidateMoveRequest,
)
from app.models.responses import (
    AnalysisResult,
    AnalyzeGameResponse,
    AnalyzePositionResponse,
    BestMoveResponse,
    EngineInfoResponse,
    ErrorDetail,
    ErrorResponse,
    EvaluateResponse,
    Evaluation,
    GameSummary,
    HealthResponse,
    LegalMove,
    LegalMovesResponse,
    MoveAnalysis,
    MoveType,
    MultiPVResponse,
    PositionInfo,
    ValidateFenResponse,
    ValidateMoveResponse,
    Variation,
)

__all__ = [
    # Requests
    "BestMoveRequest",
    "EvaluateRequest",
    "MultiPVRequest",
    "ValidateMoveRequest",
    "LegalMovesRequest",
    "AnalyzePositionRequest",
    "AnalyzeGameRequest",
    "ValidateFenRequest",
    # Responses
    "Evaluation",
    "BestMoveResponse",
    "EvaluateResponse",
    "Variation",
    "MultiPVResponse",
    "MoveType",
    "ValidateMoveResponse",
    "LegalMove",
    "LegalMovesResponse",
    "AnalyzePositionResponse",
    "MoveAnalysis",
    "GameSummary",
    "AnalyzeGameResponse",
    "PositionInfo",
    "ValidateFenResponse",
    "EngineInfoResponse",
    "HealthResponse",
    "ErrorDetail",
    "ErrorResponse",
    "AnalysisResult",
]
